[project]
name = "a4a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.21.0",
    "google-cloud-aiplatform[adk,agent-engines]>=1.132.0",
    "python-dotenv>=1.2.1",
]
